# Simple workflow for deploying static content to GitHub Pages
name: Deploy Game to Web

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm install
      - run: npm ci
      # - run: npm test # no tests to run
      - run: npm install webpack webpack-cli --save-dev
      - run: npm install --save-dev @babel/core @babel/preset-env babel-loader

      # pack the files with Webpack
      - name: Webpack JS files for web
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GHPUBLISH }}
          known_hosts: 'placeholder'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --exclude 'node_modules' --exclude '.git' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/dsector/
